### PR TITLE
Fix type and unset variables

### PR DESCRIPTION
**Pull request by marienfressinaud**

### CODE REVIEW

**Comment by kevinpapst** [comment]
I guess you know what you are doing, so I can merge without giving it a second thought...

Is this a draft or ready for merge?

**Comment by marienfressinaud** [comment]
Should be good to merge :+1: 

Making the extension for users will require an action from them to re-enable the extension though.

**Comment by kevinpapst** [comment]
Okay, I only run a single user instance, so I never tried that.
Should we mention in the README? Or do we silently ignore it?

**Comment by marienfressinaud** [comment]
Just added a mention in the changelog, I hope it's enough

**Review by kevinpapst — APPROVED** [review]
LGTM 👍

**Comment by kevinpapst** [comment]
Thanks again!

**Comment by kevinpapst** [comment]
One last wish: https://github.com/FreshRSS/Extensions/pull/68

**Pull request merged**
